name: Build Linux
on: 
  - release
  - workflow_dispatch
jobs:
  buildLinux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          path: blender
      - name: create lib folder & fetch precompiled libs
        run: |
          mkdir -p lib
          cd lib
          svn checkout https://svn.blender.org/svnroot/bf-blender/tags/blender-2.93-release/lib/linux_centos7_x86_64
      - name: build
        run: make
        working-directory: blender
