name: Build Linux
on: 
  - release
  - workflow_dispatch
jobs:
  buildLinux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          path: blender
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git subversion cmake libx11-dev libxxf86vm-dev libxcursor-dev libxi-dev libxrandr-dev libxinerama-dev libegl-dev
          sudo apt-get install -y libwayland-dev wayland-protocols libxkbcommon-dev libdbus-1-dev linux-libc-dev
      - name: create lib folder & fetch precompiled libs
        run: |
          mkdir -p lib
          cd lib
          svn checkout https://svn.blender.org/svnroot/bf-blender/tags/blender-2.93-release/lib/linux_centos7_x86_64
      - name: build
        run: make
        working-directory: blender
